# Generated by Django 3.1.7 on 2021-03-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_page_url'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='page',
            index_together={('id',)},
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
    ]
